application: Game Server1
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: (new_user.php)
  script: new_user.php

- url: (upload_file.php)
  script: upload_file.php


- url: .*
  static_files: error.html
